### ISSUE TITLE
MultiTileEntity TODO

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT-New-Horizons-Modpack#10742]
# Multi Tile Entity TODO 

## Base MTE
- [x] Inventory Proxy
- [x] Inventory GUI
- [x] Inventory Pinning via GUI
- [ ] Fluid Proxy
- [x] Fluid GUI
- [ ] Energy Proxy
- [x] Controller GUI
- [x] Recipe Handling
- [ ] Handle ticking Covers on the Controller
- [ ] Ensure the MTE is properly marking the chunk(s) dirty
- [x] Sound Handling
- [ ] MultiPass rendering improvements
- [ ] Textures :-/

## MultiBlock MTE
- [ ] Finish Texture support for MTE & Multiblocks
- [ ] Add usage of optional upgrade blocks
- [ ] Add functional casings, requirements, and multiblock tiering calculations
- [ ] Finish inventory/fluid expansion based on component parts (related to optional upgrade blocks)
- [ ] Draw dots in structure hologram, depending on allowed functional casings
