### ISSUE TITLE
Todo list for ModularUI migration

### ISSUE THREAD

**Issue by miozune** [GTNewHorizons/GT-New-Horizons-Modpack#11838]
## Mods to migrate
- [x] GregTech https://github.com/GTNewHorizons/GT5-Unofficial/pull/1381
- [x] BartWorks https://github.com/GTNewHorizons/bartworks/pull/239, https://github.com/GTNewHorizons/bartworks/pull/246
- [x] Crops++ https://github.com/GTNewHorizons/Crops-plus-plus/pull/49
- [x] Electro-Magic Tools https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/52
- [x] GalaxySpace https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/53
- [x] Good Generator https://github.com/GTNewHorizons/GoodGenerator/pull/110
- [x] GTNH: Lanthanides https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/43
- [x] GT++ https://github.com/GTNewHorizons/GTplusplus/pull/440
- [x] HydroEnergy https://github.com/GTNewHorizons/HydroEnergy/pull/19
- [x] KekzTech https://github.com/GTNewHorizons/KekzTech/pull/49
- [x] KubaTech https://github.com/GTNewHorizons/KubaTech/pull/35, https://github.com/GTNewHorizons/KubaTech/pull/34
- [x] GT: New Horizons https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/447
- [x] TecTech https://github.com/GTNewHorizons/TecTech/pull/114

## Codes to migrate
- Remove all the references to `GT_Container`, `GT_GUIContainer`, `GT_GUIScreen`, and their subclasses
- Remove all the references to `IHasWorldObjectAndCoords#openGUI`
- Remove all the references to `GT_CoverBehaviorBase#getClientGUIImpl` and `GT_CoverBehavior#getClientGUI`
- Use ModularUI in instances of `GT_Recipe_Map` if it's using `GT_NEI_DefaultHandler` or its subclass to display recipe on NEI

PRs from anyone are appreciated. Feel free to ping or DM me on Discord if you have any questions.

**Comment by Dream-Master** [comment]
beside Kuba tec all done.

**Comment by miozune** [comment]
Completed. Some mods like GT++ still have GUIs that directly extend `GuiContainer` or `Container`, but at least none of the addons use `GT_GUIContainer` or `GT_Container`, except for TecTech multiblock GUI left for backcompatibility.
