### ISSUE TITLE
2.2.8 todo list

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#12051]
Stuff delaying the 2.2.8 release:
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/211
- [x] https://github.com/GTNewHorizons/Realistic-World-Gen/pull/4
- [x] https://github.com/GTNewHorizons/GTplusplus/pull/399
- [x] https://github.com/GTNewHorizons/GoodGenerator/pull/115
- [x] https://github.com/GTNewHorizons/GoodGenerator/pull/119

**Comment by Impos913** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11971 can this also be looked into?
