### ISSUE TITLE
Ender IO & AE2 Stuff: Tiles ghost loading chunks all the time (with lags)

### ISSUE THREAD

**Issue by Pilzinsel64** [GTNewHorizons/GT-New-Horizons-Modpack#12534]
### Your GTNH Discord Username

Pilzinsel64#5440

### Your Pack Version

latest dev version of AE2 Stuff, AE2, Ender IO

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

The Issue: 
As soon as a ME Conduit from Ender IO is connected into an active ME System and this chunk(s) where the ME System is in should get unloaded (e.g. you log out or you go away), the ME Conduits prevents this chunk(s) from getting unloaded completely and cause server lags (depending on server performance it even crashes or maybe you don't have any performance impact).
As soon as the ME Conduits call `GridNode.destroy()`, the GirdNode want to validate this GirdNode and it's connections. During the validation it creates a new Grid explicitely for this GridNode when it hasn't one. This forces ME Conduits to live forever, as they tries to unload and destroy the GridNode again and again and again.
The ME Cables from AE2 doesn't have that behavior.

The AE2 Stuff bock tiles have a similar issue. They do also chunkload but as my current knowledge via Debugging they seems to destroy mostly correctly but then - not sure why and how - they get created as new object by AE2. There needs more research here.

What is my workaround for my server?
I modified and installed the mod ChunkPurge, so it purges (force unload all unneeded chunks) all 5 seconds for five ticks (one "purge all" each tick). It won't work with only one purge command, it only works if I do that more ticks in a row (for my Server at GPortal 5 ticks is enough, for my private backup server, I don't know what high value needs to be required, look the video).

### The Reality

What should happen instead:
Let the chunks unload as all conduits and me cables.
Also, don't need "ChunkPurge" to force unload that reluctantly ME Conduits.

### Your Proposal

How to reproduce - Ender IO:
Install AE2 into mod of your run folder at the Ender IO repository and run gradlew run. Get a small ME system to run (only needs a ME cable, power and and ME Terminal). Use at least one ME Conduit instead of ME Cable.

How to reproduce - AE2 Stuff:
Install AE2 into mod of your run folder at the Ender IO repository (yea, I was too lazy to create a new test world) and run gradlew run. Get a small ME system to run (only needs a ME cable, power and and ME Terminal). Use at least one AE2 Stuff mashine.

Also probably related:
~~- I already checked the source code of your Ender IO fork (I use this mod for my own private modpack). But sadly, I have not enough knowledge about mod dev and time to look into that issue deeper.~~
- I can't tell you if that bug exists today in up-to-date a Ender IO version for MC 1.12.2, only using 1.7.10. I also never found any issue directly related to this on the original GitHub repo of Ender IO. But I know (long time ago when researched that issue) I found at least one comment that mentions that (and also that it's fixed, but not sure yet, can'T find it again) and some GitHub issues that sounds similar to this, but not exactly the same (maybe they just didn't found out the real issue is about ME Conduits). 

Discussion on Discord:
https://discord.com/channels/181078474394566657/603348502637969419/1073172049171845220

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### Todo
- [ ] Fix Ender IO ME Conduits https://github.com/GTNewHorizons/EnderIO/pull/115
- [x] Fix AE2 Stuff block tiles https://github.com/GTNewHorizons/ae2stuff/pull/8

**Comment by Tommeh1** [comment]
From my experience the ME cables do also share this behavior, triggering non-stop loads and unloads if any part is not forcefully chunkloaded, grinding the server to a near halt.

**Comment by Pilzinsel64** [comment]
For us it only happens for the Ender IO ME Conduits, not for the other stuff from AE2. Only this specific conduits have that behavior for us.
So, I'm 100% sure that the Ender IO conduits ends up in a loop for some reason and keeps the Chunk loaded even if they don't want to (I seen the code, it's suposed to let the chunk unload normally but the code of me conduits seems to be broken probably at one single point that nobody can find yet).

Here an screen I took after lefting the base of someone that has an ME System with ME Conduits:
![grafik](https://user-images.githubusercontent.com/23138465/217898767-cb216100-d9ac-4583-98ab-4e95c2c551fe.png)

**Comment by Dream-Master** [comment]
@Pilzinsel64 Leitungsverbinder :trollface: hab noch nie auf deutsch gespielt.

**Comment by Pilzinsel64** [comment]
@Dream-Master I really don't know why it is called "Leitungsverbinder" as this name doesn't come up on any point in-game. Translated it's meant "Conduit connector". I wonder why it doesn't get called Me conduit" e.g. So maybe this is a hint, not sure.

**Comment by Pilzinsel64** [comment]
What is the purpose of adding the destroying GridNode to a new Grid and execute a GridChanged on this point? Anyone an idea?
![grafik](https://user-images.githubusercontent.com/23138465/225730053-e297ec90-ee0f-4ce6-a835-14b5f6780ea2.png)
The ME Conduits from Ender IO are not able to see if a GridNode is destroying or not, at least not via the API. So, it keeps everything alive and do chunkloading.
I've spend so many days to find the issue and I always come back to this point while debugging.

Btw, the whole stack trace:
![grafik](https://user-images.githubusercontent.com/23138465/225730601-d4846b76-8823-4ed2-bb6b-5dd44480005e.png)
![grafik](https://user-images.githubusercontent.com/23138465/225730584-fc131263-3000-4cfb-af66-f03121437007.png)

**Comment by Pilzinsel64** [comment]
Btw @Dream-Master can you re-open this issue, please? It's still valid as my PR wasn't . xD

**Comment by Pilzinsel64** [comment]
Alright, I've finally fixed the bug in AE2 itself. It seems the API changed over the time and AE2 has problems on destorying the node itself. This code change does fix the Ender IO conduits:
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/commit/80b7b95865a44e515629a6b5e148c05495c04559
Ender IO was not able to prevent handling such a Grid change. Wit this change the problem has been fixed and there seems to be no code changes.
As soon as I tested it also on our backup/test server, I'll PR that changes!

However, I've detected that AE2 Stuff blocks (Inscriber, etc.) also have a similar chunkloading problem. The difference to Ender IO ME Conduits is that the AE2 Stuff blocks seems to re-create itself, so I can't use a variable that defines if the block object is destroyed. No clue why it does that, but it shouldn't. It should forge destroying the object and remove from world instead of re-creating itself.
Since the code is Scala, I'm probably not able to find or fix that problem myself (and I'm still trying to... it's f*cking annoying).

**Comment by Dream-Master** [comment]
@Pilzinsel64 issue is reopen. Can you push the ae2 fix ? so it mean the backbone cables can be fixed ?

**Comment by Pilzinsel64** [comment]
@Dream-Master Thanks!
Sure, I can push the changes, so everyon can help testing it. But it hasn't to do anything with Backbones. It's a raw chunkloading problem.

**Comment by Dream-Master** [comment]
ah ok

**Comment by Pilzinsel64** [comment]
After I finished fix for ME Conduits I'm now looking and testing around the AE2 Stuff code.

All Tiles from AE2 Stuff (e.g. inscriber or grower) have two problems:
1. It calls `AEApi.instance().createGridNode(this)` directly after `node.destroy()` but then keeps `initialized` on `false`.
This opens a loop whenever the chunk wants to unload. This commit seems to fixes it: https://github.com/GTNewHorizons/ae2stuff/compare/master...Pilzinsel64:ae2stuff:fix-chunkloading
Please tell me, if I'm wrong here.
2. There seems to be another bug that triggeres a re-creation of all Grid elements (also our Tile) whenever the chunk has been unloaded and AE2 Stuff tiles has been used within this Grid.

But let's describe the 2nd point a little bit more detailed what I've found out:
  - Minecraft wants to unload the chunk
  - all Grid elements destroy, also our inscriber destroy
  - at the next server tick, all Grid elements (also our inscriber) get re-created
  --> *but **only** if the Grid contains a AE2 Stuff tile (e.g. inscriber)*

What could be the problem here? It seems as the AE2 Stuff tiles doesn't get removed from a kind of tile list, so the next server tick wants to tick each tile in its list and our Grid (or only a part of it) is still in this ist. But I have no clue where or what I need to search in the code. I'm not even sure if the bug comes from AE2 Stuff or from AE2 itself. That I'm not fimilar with scala doesn't make it better...

@eigenraven @repo-alt You know the AE2 code better then any other, as what I know. Do you have any idea or suggestion where I can search or what I can test here?

This is my very small grid setup with a AE2 Stuff tile (grower):
![grafik](https://user-images.githubusercontent.com/23138465/226557393-deab6d8f-4478-4de5-a83f-53714592d1cb.png)
Gif showing that the chunks are still there: https://cloud.pilzinsel64.de/s/GE72taaYK95Xbw9

**Comment by Pilzinsel64** [comment]
Both mods got a fix via PR, so this Issue can be closed now.
Thank you @repo-alt for the quick fix for AE2 Stuff!

**Comment by Pilzinsel64** [comment]
As of https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/295 has been merged, the fix for Ender IO ME Conduits is not valid anymore.

I am despairing, not sure how to fix.
Any help is welcome!

**Comment by trollolal** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13065
Not sure is it the same issue

**Comment by Pilzinsel64** [comment]
> #13065 Not sure is it the same issue

This should be fixed with https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/295
