### ISSUE TITLE
Todo: disable tinkers gregworks recipes and create extruder recipes instead

### ISSUE THREAD

**Issue by Fiyorin** [GTNewHorizons/GT-New-Horizons-Modpack#13401]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.3.3-nightly

### Original Request

replace tgregworks large plate recipes with avaritia ones

### Responding developer

@DreamMasterXXL

### Context

https://discord.com/channels/181078474394566657/522098956491030558/1102588764225798264

### Developer's Promise

"ok we get disable Tgregworks but we need to add recipes via Extruder later when kuba did all recipes in code"
"remove TGregworks part in the future"

currently kuba is porting scripts to code

it's related to: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13391

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by Fiyorin** [comment]
@Dream-Master is this finished now? saw these changes: <https://github.com/GTNewHorizons/TecTech/commit/8e354d125b3aa5a328e8019a9b2838a6e507a684>

**Comment by miozune** [comment]
still not fixed

**Comment by Dream-Master** [comment]
it is fixed. Tgregworks not have Bedrockium as material so we use the Extra Utilities Avaritia one

**Comment by miozune** [comment]
Bedrockium is, but Infinity and Cosmic Neutronium are not

**Comment by Dream-Master** [comment]
they have 2 kind of the same materials. 
1. we keep one type of it
2. we keep both type of it
