### ISSUE TITLE
Adding new machine type: Drone Centre

### ISSUE THREAD

**Issue by RealSilverMoon** [GTNewHorizons/GT-New-Horizons-Modpack#14972]
### Your GTNH Discord Username

real_silver_moon

### Your Pack Version

2.4.0

### Your Proposal

With an increasing number of machines, we lack a centralized control device similar to AE2's interface terminal for quick management. Add a central controller device to GT5 that can efficiently control a wide range of multiblock machines.
_**Actually, it's because I had a power failure a few days ago—the Lapotronic super capacitor shut down. I had to go around with a soft hammer to reboot the mainframe for the multiblocks. It was truly painful. And I don't want a wireless redstone receiver and switch cover on top of each machine.**_

### Function
- Display the list of linked machines.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/489734c2-7e0e-4467-957e-81abd4d72ab4)
- Turn on/off specified machine
![NVIDIA_Share_Z8TJTMxrhZ](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/18166672-af39-4931-be52-e81792cbf0bd)
- Turn on/off all linked machines
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/ba7ec117-c446-45eb-9e65-7bc0a4cd8235)
- Highlight selected machine (works just like interface terminal)
![NVIDIA_Share_JjZyCgkAhk](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/a799a468-6640-4f99-a2bc-42abd8a2221c)
- Auto maintaining
- Set custom name
![NVIDIA_Share_lsWoDWyiWn](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/d2390a2f-c789-453b-9c6c-025e6094e044)

### Structure:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/bc71bfe9-0ff5-4c32-8de3-1be13b37c5fa)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/81dd128f-022a-4b61-a7aa-732d1e769655)
### Running:
- Build the structure.
- Replace maintenance hatch on other multi with drone downlink module.
- Place drones in input bus. **Influence the machine's operating range and probability of drone breakdown.**
- Run the drone centre. The module will connected to centre automatically and fix all issues.
- Currently this machine does not require power to run, but will cost drones depend on drone level. 
- Every 10 seconds, there is a probability of 0.028%*(3-drone level) for the drone to crash. Once crashed, all machines connected to the Drone Maintenance Center will start getting random issues until a new drone is inputted. 
-  The expected average time for 1 drone consumption: T1 - 1 hour , T2 - 2 hours, T3 - Unbreakable.
### Todo
- Recipe. There are no recipes for mainframe and drones. Which tier should this machine be placed ? The initial thought is T1-IV or LUV, T2-ZPM, and T3-UHV
- Range. The operational range of the Drone Maintenance Center needs to be determined based on the drone level. I'm not sure how long should i set for there-tierd-drones.
- More models. I only draw a model for drone Tier 1. It would be better if someone could help draw T2 & T3 models. (Or they can share model with T1...)

### Your Vision

Since the temporary halt in mutes development, I proceed this multiblock machine as traditional multiblock . Once mutes is complete and all machines are converted to mutes (if this does happen), the Drone Center can be rewritten as mutes. Currently, it performs well in integrated switching tasks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Hikari1nVoid** [comment]
sounds more like a trolling machine comparing to regular auto-tapers...I'm out.

**Comment by vovaksenov** [comment]
Are the textures here final? They look extremely out of place tbh. Id stick to 16x16. Also the drone color scheme looks like a missing texture error, maybe use some darker colors

**Comment by Dream-Master** [comment]
Ok feature freeze is over so lets talk about this device.

**Comment by Eranicus** [comment]
The idea is good for end game bases. (the ability to turn off whole base or its sections and to rename machines) I can confirm that if you use wireless covers on every machine at end game base, the lag will be big.

The question is will this machine lag compared to wireless covers ? considering it is somehow monitoring all the machines.

**Comment by RealSilverMoon** [comment]
> The idea is good for end game bases. (the ability to turn off whole base or its sections and to rename machines) I can confirm that if you use wireless covers on every machine at end game base, the lag will be big.
> 
> The question is will this machine lag compared to wireless covers ? considering it is somehow monitoring all the machines.

Test on my server (DIM-1052) :
Before:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/eeb022fb-3c3a-48a6-a924-0b6cc6f4a86c)
After:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/38f6aa61-12ca-4fa2-9b39-e86acfc2dbfd)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/189d5cd9-0241-4c70-ad7a-55135350c967)
With 156 machine connected, drone centre cause no any lag (TPS even got better!) 
Technically, the centre doesn't do much on each tick. It just collect connection passively and show them when you open the GUI. The downlink will search for mainblock, try connecting to centre and check validity. These work only trigger every 5/10 seconds until it has a vaild connection, then it just sleep.
