### ISSUE TITLE
Issues list for 2.5.0

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#15013]
This is list of issue that need to be or should be fixed for 2.5.0. If you are a dev/admin, feel free to edit to add more/move around/etc.

### Bigger issues that need fixing for 2.5.0
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14644
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15012
- [x] https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/109
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15045
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15048
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15060
- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15069~~ @GDCloudstrike said it's normal

### Smaller issues that would also be nice to have fixed
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15031
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12620
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14804
- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14631~~ - glee8e has some plans but this might be too big of a rework for 2.5.0. delayed
- [x] https://github.com/GTNewHorizons/Hodgepodge/issues/285 (not actually breaking anything but puts 10 useless extra errors in every log)
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14964
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15070
- [x] https://github.com/GTNewHorizons/KekzTech/pull/79
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15082
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13955
- [ ] #12796 

### Potential issues that need testing/confirmation/details
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14960
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14845
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15006
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15018
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14620

**Comment by bombcar** [comment]
- [ ]  https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13955 - was on 2.4.0 and is a "nice to fix"

**Comment by Ethryan** [comment]
#14170 
Link since it still contains a few open subjects.

**Comment by chochem** [comment]
was released a while back
