### ISSUE TITLE
TODO i18n for zh_TW

### ISSUE THREAD

**Issue by Chococar-NSW** [GTNewHorizons/GT-New-Horizons-Modpack#15287]
### Your GTNH Discord Username

chococar

### Your Pack Version

2.5.1

### Your Proposal

I want localization GTNH with traditional Chinese.
If you want know detail, see [this](https://en.wikipedia.org/wiki/Traditional_Chinese_characters)
Make a long story short.
This two writing system, they are same mean in the similar character, but not the same character in Unicode.
It's annoying when someone can't search right thing in NEI.
And some of my friend because the language gap, doesn't want play this pack.
So this is a big project, because I'm the only one for this, maybe need some help from traditional Chinese native speaker

DISCLAIMER: This translate will reference zh_CN and replace some term that is not using in traditional Chinese.

### Your Goal

- [ ] GT5-Unoffical (Current Working)https://github.com/GTNewHorizons/GT5-Unofficial/pull/2440
- [ ] GT++
- [ ] bartwork
- [ ] TecTech

### Your Vision

Make those ungrateful friend play this pack.
Pain together.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.
