### ISSUE TITLE
todo list for 2.6.0

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#15690]
### Bigger issues that need fixing for 2.6.0
- [x] ~~https://github.com/GTNewHorizons/GTNH-Translations/issues/8~~ DAXXL doesn't ship a translated file anymore if it clashes with the default one, so we can skip this.
- [x] https://github.com/GTNewHorizons/Angelica/issues/370
- [x] finish ~~https://github.com/GTNewHorizons/CarpentersBlocks/pull/6~~ https://github.com/GTNewHorizons/CarpentersBlocks/pull/7 so the carpenters render correctly
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14620
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15172
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15716
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15702
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15739
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15746
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15794
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15826
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15880
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15848, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15836
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15972, https://github.com/GTNewHorizons/Angelica/issues/214
- [x] https://github.com/GTNewHorizons/Angelica/issues/425
- [x] migrate the space elevator cable rendering from angelica to GTNH-Intergalactic
- [x] https://github.com/GTNewHorizons/Angelica/issues/379
- [x] https://github.com/GTNewHorizons/Angelica/issues/431
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15957

### Smaller issues that would also be nice to have fixed
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15155
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15334
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15689
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15563
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15214
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15565
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15605
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15608 (https://github.com/GTNewHorizons/GT5-Unofficial/pull/2537, https://github.com/GTNewHorizons/GTplusplus/pull/849, https://github.com/GTNewHorizons/GT5-Unofficial/pull/2538)
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15631
- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471~~
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15706
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15709
- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15647~~ (after 2.6.0, would basically be a feature addition)
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15742
- [x] https://github.com/GTNewHorizons/WitcheryExtras/pull/21
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15719
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15646
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15779
- [ ] potentially update server list with some of: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15770, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15769, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15700, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12705, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11573 (or say no and close them)
- [ ] https://github.com/GTNewHorizons/Angelica/issues/390
- [ ] https://github.com/GTNewHorizons/Angelica/issues/185
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15802, https://github.com/GTNewHorizons/Angelica/issues/383, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15816
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15808
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15799
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15809
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15523
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15865
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15890
- [x] https://github.com/GTNewHorizons/twilightforest/issues/53 (resolved for GTNH)
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15898
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15923
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15949
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15952
- [ ] https://github.com/GTNewHorizons/lwjgl3ify/issues/137
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14075
- [x] #15637

### Potential issues that need testing/confirmation/details
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15677
- [x] ~~https://github.com/GTNewHorizons/GoodGenerator/pull/246~~ (frozen)
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15765
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15918
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15603
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15798
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15796
- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15786~~
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15840
- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15841~~ (likely user error)
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15878
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15881
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15863
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15886
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15731
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15914
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15778
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15928

#### AE2
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/470
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/487
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/485
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/488

#### AE2FC
- [x] ~~https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/189~~ Will be reworked later 

#### Better Loading Screen
- [x] https://github.com/GTNewHorizons/BetterLoadingScreen/pull/24

#### Better Questing
- [x] https://github.com/GTNewHorizons/BetterQuesting/pull/132 added for testing
- [x] https://github.com/GTNewHorizons/BetterQuesting/pull/130 added for testing
- [x] ~~https://github.com/GTNewHorizons/BetterQuesting/pull/127~~ Delayed for the 2.7.0

#### Botania
- [ ] https://github.com/GTNewHorizons/Botania/pull/42
- [x] https://github.com/GTNewHorizons/Botania/pull/46

#### BugTorch
- [ ] https://github.com/GTNewHorizons/BugTorch/pull/22

#### Chisel
- [x] https://github.com/GTNewHorizons/Chisel/pull/47

#### FindIt
- [x] https://github.com/GTNewHorizons/FindIt/pull/14

#### Giga Gram Fab
- [ ] https://github.com/GTNewHorizons/GigaGramFab/pull/29

#### Good Generators
- [x] ~~https://github.com/GTNewHorizons/GoodGenerator/pull/228~~ Delayed until we find what are all the implications of the shortcuts in this PR.
- [x] https://github.com/GTNewHorizons/GoodGenerator/pull/239
- [x] https://github.com/GTNewHorizons/GoodGenerator/pull/241
- [x] https://github.com/GTNewHorizons/GoodGenerator/pull/242

#### GraviSuite Neo
- [x] https://github.com/GTNewHorizons/Gravitation-Suite-Neo/pull/19
- [x] https://github.com/GTNewHorizons/Gravitation-Suite-Neo/pull/18

#### GT5U
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2417
- [x] ~~https://github.com/GTNewHorizons/GT5-Unofficial/pull/2502~~ Delayed for the 2.7.0
- [x] ~~https://github.com/GTNewHorizons/GT5-Unofficial/pull/2507~~ Delayed until we find time to test and find all the implications of such bee effect.
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2522
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2525
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2528
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2529
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2531
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2532
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2533

#### GT++
- [x] https://github.com/GTNewHorizons/GTplusplus/pull/840
- [x] https://github.com/GTNewHorizons/GTplusplus/pull/846

#### GTNH-Intergalactic
- [ ] https://github.com/GTNewHorizons/GTNH-Intergalactic/pull/9

#### GTNH Lib
- [x] ~~https://github.com/GTNewHorizons/GTNHLib/pull/26~~ deferred

#### IronChests
- [x] https://github.com/GTNewHorizons/ironchest/pull/19

#### Magic Bees
- [x] https://github.com/GTNewHorizons/MagicBees/pull/32

#### Malisis Doors
- [x] https://github.com/GTNewHorizons/MalisisDoors/pull/14

#### Modpack
- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15550~~ very low priority
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15664
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15668
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15674

#### NHCore
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/763 or https://github.com/GTNewHorizons/GT5-Unofficial/pull/2534
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/806
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/819

#### NEI Custom Diagrams
- [x] ~~https://github.com/GTNewHorizons/nei-custom-diagram/pull/30~~ Delayed for the 2.7.0

#### RWG
- [ ] https://github.com/GTNewHorizons/Realistic-World-Gen/pull/16

#### Spice of Life
- [ ] https://github.com/GTNewHorizons/SpiceOfLife/pull/32

#### TecTech
- [x] https://github.com/GTNewHorizons/TecTech/pull/273

#### TC NEI Additions
- [x] https://github.com/GTNewHorizons/TCNEIAdditions/pull/25

#### Twilight Forest
- [x] ~~https://github.com/GTNewHorizons/twilightforest/pull/50~~ Delayed for the 2.7.0
- [x] https://github.com/GTNewHorizons/twilightforest/pull/41
- [x] https://github.com/GTNewHorizons/twilightforest/pull/36
- [x] ~~https://github.com/GTNewHorizons/twilightforest/pull/44~~ Delayed for the 2.7.0

#### Visual Prospecting
- [x] https://github.com/GTNewHorizons/VisualProspecting/pull/39

**Comment by AbdielKavash** [comment]
As far as I know this has *still* not been fixed over two major versions, and it forces ugly workarounds for big AE systems.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14620
