### ISSUE TITLE
Todo list for 2.6.1

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#16143]
### **PRs to add for 2.6.1:**

**GTNH (config repo):**
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/17b7680071bb1932210a99c47ab5de7b749a9326 (disable cascading worldgen spam in AF config)
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15994
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16145
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16203

**AE2FC:**
- [x] https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/206

**AE2:**
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/512
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/514
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/513
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/515
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/517

**Angelica:**
- [x] https://github.com/GTNewHorizons/Angelica/pull/453
- [x] https://github.com/GTNewHorizons/Angelica/pull/447
- [x] https://github.com/GTNewHorizons/Angelica/pull/456
- [x] https://github.com/GTNewHorizons/Angelica/issues/404
- [x] https://github.com/GTNewHorizons/Angelica/issues/421

**BattleGear2:**
- [x] https://github.com/GTNewHorizons/Battlegear2/pull/28

**BQ:**
- [x] https://github.com/GTNewHorizons/BetterQuesting/pull/136

**Blood Magic:**
- [x] https://github.com/GTNewHorizons/BloodMagic/pull/51

**Carpenters Blocks:**
- [x] https://github.com/GTNewHorizons/CarpentersBlocks/pull/10

**Computronics:**
- [x] https://github.com/GTNewHorizons/Computronics/pull/23

**EnderStorage:**
- [x] https://github.com/GTNewHorizons/EnderStorage/pull/11

**Ender IO:**
- [x] https://github.com/GTNewHorizons/EnderIO/pull/162

**Gendustry:**
- [x] https://github.com/GTNewHorizons/gendustry/pull/9

**GigaGramFab:**
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16130 (Confirmed to happen with any recipe that used renamed items in a stocking bus)

**Good Generator:**
- [x] https://github.com/GTNewHorizons/GoodGenerator/pull/255 

**GT5U:**
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2590
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2578
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2579
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2596
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/2592

**GTPP:**
- [x] https://github.com/GTNewHorizons/GTplusplus/pull/871
- [x] https://github.com/GTNewHorizons/GTplusplus/pull/880
- [x] https://github.com/GTNewHorizons/GTplusplus/pull/878

**Harvestcraft:**
- [x] https://github.com/GTNewHorizons/harvestcraft/pull/59

**HodgePodge:**
- [x] https://github.com/GTNewHorizons/Hodgepodge/pull/359

**Holo Inv:**
- [x] https://github.com/GTNewHorizons/HoloInventory/pull/45

**HydroEnergy:**
- [x] https://github.com/GTNewHorizons/HydroEnergy/pull/24

**Kekztech:**
- [x] https://github.com/GTNewHorizons/KekzTech/pull/87
- [x] https://github.com/GTNewHorizons/KekzTech/pull/88
- [x] https://github.com/GTNewHorizons/KekzTech/pull/90

**Lanthanides:**
- [x] https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/88

**lwjgl3ify:**
- [x] deadkeys are fixed in https://github.com/GTNewHorizons/lwjgl3ify/releases/tag/2.0.8

**NHCore:**
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/827
- [x]  https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/840
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/841
- [x]  https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/842
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/826
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/843
- [x]  https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/844
- [x]  https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/845
- [x]  https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/846
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/850
- [x]  https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/851

**Tectech:**
- [x] https://github.com/GTNewHorizons/TecTech/pull/280

**Twilight Forest:**
- [x] https://github.com/GTNewHorizons/twilightforest/pull/63
- [x] https://github.com/GTNewHorizons/twilightforest/pull/68

**WAWLA:**
- [x] https://github.com/GTNewHorizons/WAWLA/pull/6

**WitchingGadgets:**
- [x] https://github.com/GTNewHorizons/WitchingGadgets/pull/51

**Comment by chochem** [comment]
2.6.1 was released.
