### ISSUE TITLE
2.7.1 release

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#18274]
bugs we absolutely need to fix before release:
- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18273~~ user error, caused by config driven blocks
- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18275~~ user error, caused by config driven blocks
- [ ] [Share-where-I-am is broken with recent versions of VisualProspecting](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18324)
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18288, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18265

minor bugs we should fix before release:
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18322
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18323
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18287

PRs to add in 2.7.1:
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3618
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3619
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/18284
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3515
- [x] https://github.com/GTNewHorizons/GTNH-Intergalactic/pull/88
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/618
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/614
- [x] https://github.com/GTNewHorizons/Infernal-Mobs/pull/17
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3485
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3560
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3565
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3586
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3527
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3590
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3615
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3616
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3624
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1103
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1106
- [x] https://github.com/GTNewHorizons/GT5-Unofficial/pull/3652

tickets to investigate:
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18239
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18320
