### ISSUE TITLE
Bring back better bees

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4478]
Action items for bees.

- [ ] #4252 Make more bee breeding quests. Add some reward bees that can help with the tedium of breeding. (reward ideas - robust bee, steadfast/valiant as  quest reward, clay bee as lootbag reward) More reward ideas please, both for quests and lootbags. Apiary suit bits? Cloths?
- [x] #4501 Make more bee quests - frames, alveary upgrades, GenDustry.
- [ ] #4505 Add a new recipe that uses the bee comb + ic2 leaves to give bonus outputs. 9+9 = 16 instead of 8? 
- [ ] #4506 Add back some centrifuge recipes. Only for common low tier materials: iron, copper, tin, silver, gold. 
- [ ] #4507 Modify recipe for GT++ mutagenic frame. Take out Pu-241 since it relies on trollplant. Use only U235/U238/flamestring/proven frame. Proven frame is available from TC and from beekeeper villagers. 
- [ ] Adjust uum autoclave recipes, decrease time but increase uum - way too slow compared to just mining. Reduce by 1/3. 
- [ ] Balance nuclear bees against reactors so there is a net power gain after processing U/Pu/Th/Nq combs without a need for supplying unrenewable ores
- [ ] Add new LV Assembler recipes for extra bees frames like chocolate/soul frames/etc. Make frames cost 4x the components. Add to quest for them that there are rumors of magicians specializing in apimancy. Oblivion frame keep in TC.
- [ ] #4495 Buff Thaumcraft research bee frames so they are cheaper to make (aspect wise) and produce more output. 2x frames for example. Change them to needing 2nd tier bee waxes like refractory wax, magic, soulful, amnesic.  
- [ ] #4496 Mutator alveary block moved to EV. Electrical Stimulator block moved to IV.

**Comment by bartimaeusnek** [comment]
aree on 1,2,3 (3 only for basic materials like copper, tin, iron, lead, silver, gold),
for 4 balance against alveary please
for 5 hard no.

**Comment by Hakameda** [comment]
Ignore 1,3,4

Frames atm are useless, this would make them worth something and useful. You can't mass produce them in LV and low usage + u238 and u235.

2 is cool +1

**Comment by DietmarKracht** [comment]
1,3+!! But we need to adjust the uum autoclave recipes. increase the amount of uum needed but decrease the processing time. it is way to high atm. especially for the higher tier combs. trinium or europium take more than 6000 seconds each at their respective tier just to produce 4 purified ores, whereas chemically processing crushed ores with combs will take much less time

**Comment by kekzdealer** [comment]
1) I'd love to see some bees as rewards. One bee that I think could be a nice reward is the Robust Bee. It doesn't produce anything special, but you can use it's "Both 2" trait to get the Aluminium bee without needing any special breeding equipment. Maybe also add Clay bees to loot bags? They're used for quite some breeds but can't be bred in a normal/normal environment that is often used for bees.

2) Sounds cool?
3) I don't really think that's necessary. I'm still quite fond of combs working like ic2 crops now. 
4) I like the current tuning, but I don't feel like bees are on par with crops at all. Not sure.
5) Meh no.

**Comment by DietmarKracht** [comment]
#4357

**Comment by kekzdealer** [comment]
Oh and did I forget how you need bees that poison you up and running for a quite a long time to make the bee suit so all the other fancy bees don't kill you in various way? (:

**Comment by richardhendricks** [comment]
....
Just setup a bunch of alvearies in a row with outputs piped from 1st to 2nd etc, and side-pipes to a far away chest.  At the bottom output to the far away chest.  Put in the bees, wait for the princess to show up in your chest, no painful stings.

**Comment by bedrill64** [comment]
I'm into 1 and 2, do not know anything about centri recipes so can't relate to 3, same goes for 4, and about 5, i'm fine with plutonium in recipe, u-235 is tedious part really if you do not have steady source of uranium.

**Comment by Hakameda** [comment]
@kekz The frame speeds up early game. And you don't really mass produce them

**Comment by kekzdealer** [comment]
Frames locked behind a whole tree of research in TC? :D

**Comment by sthegreat** [comment]
1. New quests are always good.
2. Yes, maybe? On the one hand it's pretty cool and incentivizes doing both breeding types, but on the other hand bees and crops scale differently over tiers so it might be hard to keep the bee:crop ratio balanced for all game stages.
3. Only for basic materials
5. Switching to uranium: definitely not. However, the cost could be reduced significantly by changing some or all of the Pu241 to Pu239, which might be a more balanced alternative. However I'd like to keep at least a little 241 in there to give a reward for doing trollplants.

4. I think this is best addressed by reducing the times on the comb processing in the autoclave. Current times are just too long. For example, even if using the expensive gt++ autoclave, in the current dev version it's more eu efficient to produce 32 crushed uranium from 2000uum via thaumcraft and then 4x that with combs than it is to actually use the autoclave recipe for uranium combs. I would say autoclave times could be reduced by a factor of 2 to 3 (maybe increase uu input a bit if they are reduced by 3).

**Comment by yukieiji** [comment]
1. Good
2. Good
3. According to the product.
4. No problem as it is

**Comment by chochem** [comment]
5. I can't really understand the discussion. Oblivion frames exist already, are repairable, and can be found in the world (no need to craft them). I also think they should stay that way. Maybe there is some middle ground with semi-effective or non-repairable frames but breeding 100+ bees without helpful frames is madness.

**Comment by combusterf** [comment]
More bee quests: definitely. Hand out a starter collection of combs, possibly a free queen or steadfast/valiant drone.

2-4: I'd like see the nuclear bees balanced against reactors, so you can get a net power gain after processing U/Pu/Th/Nq combs without a need for supplying the unrenewable ores.

5: Ic2 crops' real problem is that they are not walkaway-safe, unlike bees. Rather to have something for that issue instead of getting them outbuffed by everything else.

**Comment by richardhendricks** [comment]
It's called WeedEx 😒

**Comment by richardhendricks** [comment]
@chochem They are gated pretty hard right now.  I don't think the spawn rate in the world is going to make much difference, especially for a server. I do like the idea of a middle ground. How about a frame with the normal 80 uses that lowers lifetime but is based off of Grin Powder. That needs a Venomilia crop to make. A frame that lowered lifespan by 50% each, with 3 frames in an apiary is only 12.5% lifespan.  I think that's fair. And if you want insta-death you can wait until you have uranium/plutonium.

**Comment by richardhendricks** [comment]
I have updated the original comment with voting results and captured some suggestions up there for tl;dr.

**Comment by chochem** [comment]
@richardhendricks iirc they are pretty common in strongholds. I found mine very quickly but maybe I was lucky. Obviously stuff like that is harder on a server.

Anyway, I like your proposal.

**Comment by richardhendricks** [comment]
There are only 3 strongholds on a whole server, so yeah that's not going to be fair.

**Comment by Hakameda** [comment]
The frame should be LV/MV else it will never be worth it probably

**Comment by richardhendricks** [comment]
I'm ok with it being LV.  Lead rods, impregnated sticks, Grin powder, flamestring. :D

**Comment by richardhendricks** [comment]
THE GREAT AND MIGHTY DREAM HAS SPOKEN
![image](https://user-images.githubusercontent.com/1214811/57808453-043d4700-7729-11e9-8f2e-afff8c52da16.png)

**Comment by Hakameda** [comment]
Actually that would be cheaper , so okay for impreg sticks and flame string

**Comment by Hakameda** [comment]
It's just otherwise it's an unused thing, and it could be useful for low tier bees until late MV/HV

**Comment by richardhendricks** [comment]
After looking it over, Chocolate frames are .75 lifespan, minimum of .25 (5 frames). They aren't gated that hard by TC,  It's not hard to craft either, needing only impregnated frames, not proven frames.

Then there is soul and finally oblivion frames via further TC, so I'm leaning towards no on the new frame.  If you get an alveary you could get 5 chocolate frames and  soul frames pretty easily.

Even in an apiary 3 chocolate frames is 42% lifespan. 

Each tick is 27.5s per cycle. Getting short lifespan traits is really easy since Cultivated bees are Shortest lifespan with only 10 cycles.

 I don't know if we really need a frame before that. How about a "Sickly Frame" that is .8 lifespan but can only be stacked 3 times to 51%.  That's 5 cycles or 2.5 minutes.  I normally check my IC2 crops every 5 or so minutes so I think that's a fair time to wait until you get better frames via thaumcraft or GT++.

**Comment by richardhendricks** [comment]
When we do breeding quests we can talk about how to properly breed, using a cultivated princess with the shortest trait locked it with the new drone the player wants to mate with,

**Comment by Dream-Master** [comment]
you can add frames as reward for bee quests or put them in the bee lootbags. @richardhendricks

**Comment by richardhendricks** [comment]
yes I will do that.

**Comment by richardhendricks** [comment]
Unlocks with Upgraded Home quest
![image](https://user-images.githubusercontent.com/1214811/57902127-7a2ad680-782d-11e9-8d58-7d6e68d50d66.png)
![image](https://user-images.githubusercontent.com/1214811/57902128-7dbe5d80-782d-11e9-91d4-a78f0cb9494e.png)

Unlocks with Nether
![image](https://user-images.githubusercontent.com/1214811/57902153-93cc1e00-782d-11e9-8e05-f71861816a9b.png)

**Comment by richardhendricks** [comment]
Proposal:

Modify recipe for GT++ killing frame.  Take out Pu-241 since it relies on trollplant. Use only U235/U238/flamestring/proven frame. Proven frame is available from TC and from beekeeper villagers.

Add new LV Assembler recipes for extra bees frames like chocolate/soul frames/etc. Make frames cost 2x or 4x the components. Add to quest for them that there are rumors of magicians specializing in apimancy. Oblivion frame keep in TC.

Buff Thaumcraft research bee frames so they are cheaper to make (aspect wise) and produce more output. 2x frames for example.  Change them to needing 2nd tier bee waxes like refractory wax, magic, soulful, amnesic

**Comment by richardhendricks** [comment]
This is a change to #5 after long discussions.

**Comment by richardhendricks** [comment]
Talked with Dream, and he doesn't want to rush this for 7.3. Instead we will do a comprehensive look at bees from front to back and look at tiers etc.

**Comment by richardhendricks** [comment]
https://docs.google.com/spreadsheets/d/1Rsz0rH9tIVJxr18b1Z6-QxOSaEKssxF7u2naQTq2Mqg/edit#gid=1650436125

**Comment by richardhendricks** [comment]
Doing testing for 7.3, thoughts so far

Crops can get started way easier for cheaper, and has useful crops much sooner (see stickreed, oreberries, metal plants)

Bees depend much more heavily on tiers too. Sure you can throw together a bee house pretty early, but the best stuff you're going to get out of it is sugar if you're lucky enough to get some valiant bees.
Anything real requires apiaries.  Which is a huge time sink if you make them yourself and a bother to go find/make a beekeeper villager to buy them. Making them requires woven cotten, and both seedoil and creosote infused wood pieces.

Available frames without magic is very lackluster.

Magic frames kinda suck considering the current recipe.  Needs serious buffing.

**Comment by Hakameda** [comment]
Wasn't the first thing I said to you that crops were significantly easier the bees?

**Comment by bartimaeusnek** [comment]
unpinned for now, will repin when 2.0.7.4 is done

**Comment by sthegreat** [comment]
So here are my ideas and opinions about bees and crops:

On the topic of uum autoclave recipes (resources are generated from only the leaf/comb and uum):
Change the way that comb/leaf recipes are generated, currently they to be partially (time and uum required) autogenerated on the basis of... density(?). Bee combs however also have a tiering system, which decides the recipe eu/t. This leads to some odd behavior, for example naquadah combs are far more expensive to autoclave than lutetium, even though we can probably agree that lutetium should be the same price or more expensive. Another example is that it makes the nuclear fuel autoclave recipes, which are of special interest as many people will want to automate their fuel using bees, much more expensive than other combEv recipes due to their high density (thorium is 1470s + 24l uu, while titanium, also combEv, is 307s + 6l uu).

Instead, we should take a good look at the product tiering system and decide where everything needs to go. Then, each product in the same product tier can get an identical uu recipe, without the density weirdness causing mismatched costs. We should also use the same tiering system for crops, and use proportional recipe times and uu costs, with both divided by 4 for crops because crops are 16:1 instead of 9:4 crushed ores. This prevents the current weirdness where osmium crops have an hv autoclave recipe while the equivalent bees have a long expensive IV one.

On the topic of the ore duplication recipes: These should be done using the same system as uum recipes, and therefore be the same recipes for bees and crops. Essentially I just want to move the crop recipes to be the same as the bee ones here. We should also look at which bees can do which ores though, as currently there are some weird ones. Bee combs and crops should only be able to multiply ores for which that comb's/leaf's resource is the main product (after all processing) of that ore.

On the topic of non-ore bees, which are bees with centrifuge recipes instead of autoclave/ore processing ones: these seem mostly fine as is, but some like the infinity line should be changed to make them actually usable or removed.

**Comment by sthegreat** [comment]
Also: The 9-in-1 (gt++ autoclave) currently has a massive impact on the viability of a lot of autoclave recipes. While the machine is decently tiered, being IV but very expensive within that tier, it's 3.5x speed boost and 80% eu/t multiplier is pretty huge and totally changes things, being the only reason that some bee combs like nuclear fuels are even close to viable right now. Should the autoclave recipes be changed to a more gt++-resistant machine such as the chem reactor?

**Comment by sthegreat** [comment]
I made a spreadsheet with all the current autoclave recipes, and my proposed recipes, here:

https://docs.google.com/spreadsheets/d/1el609jCfXZWy_tSno_wsfRcRjjyH5AZsdiKNXq4L9_o/edit#gid=0

Thoughts? I wasn't totally sure on what to put for new recipes, I tried to reduce the cost overall by decreasing time significantly and increasing uu for some combs, decreasing for others so they fit tiers. Nor was I sure where to put some of the combs. These recipes are made with a change from autoclave to another machine such as chem reactor in mind due to the effect of the gt++ autoclave.

**Comment by richardhendricks** [comment]
ah ok.  I think we can collate this information under kekz ticket at https://github.com/GTNewHorizons/NewHorizons/issues/4701
It might be lost here until the tldr

**Comment by sthegreat** [comment]
Another irregularity with bees is all the extra bees/magic bees that are exact duplicates of gt bees, for example there are like 3 diamond bees, of which gt is definitely the worst. It may be a good idea to remove bees with exact gt analogues (remove breeding/outputs and add autoconvert).

**Comment by richardhendricks** [comment]
uh, that's the point of the warning message in the release?  we;'re getting rid of the gendustry bees for good in the next major update.

**Comment by sthegreat** [comment]
talking about magic bees and extra bees not gendustry. For example all the bees that give metal nuggets, the diamandi/esmeraldi bees, the bees that give crystal shards, etc.

**Comment by richardhendricks** [comment]
hmmm ok, separate issue I guess

**Comment by DietmarKracht** [comment]
If you remove the ability to obtain these magic bees you also remove the only way to get their effects

**Comment by richardhendricks** [comment]
We're not talking every magic bee, just the redundant ones.  If they have a useful/interesting effect, let me know and I can add it to one of the GT bees.

**Comment by redmage17** [comment]
I would add reducing the processing times of Binnie's Machines to 1/5  would be a huge buff. I am trying to config it but horrible at Java. Changing the integer would be easy. Also looking at the processing times and UU cost of combs myself
