### ISSUE TITLE
todo list galactic craft

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#6084]
things that should be changed

- rockets keep fuel when launching instead of in the lander
- change fuel to use rocket fuel instead of diesel
- rockets with launch controller should teleport a lot faster
- redus agro range of mobs

- [x] rockets keep fuel when launching instead of in the lander
- [x] rockets with launch controller should teleport a lot faster
- [x] change fuel to use rocket fuel instead of diesel
- [ ] redus agro range of mobs
- [x] Make Nasa workbench crafting grid bigger to put all recipes into it. (9x9 max)
- [ ] Fix oxygen tileentity lag
- [ ] make it so if no valid launch destination dont launch the rocket if using space bar
- [ ] make it so if that a rocket can launch with launch controller if no person is in it
- [ ] if you're in a rocket, you can't shift out
- [ ] fix presing space twice can stil launch the controller even if ther eisebnt enough fuel
- [ ] fix cargo rocketss from exploding whne using launch controller
- [ ] privetise frequanties of launch controller

**Comment by Dream-Master** [comment]
- Make Nasa workbench crafting grid bigger to put all recipes into it.  (9x9 max)

**Comment by Prometheus0000** [comment]
- Fix oxygen tileentity lag
- Guarantee Dungeons have Boss+Chest (generate those first?)

**Comment by Dream-Master** [comment]
we only can edit GC not GS

**Comment by Prometheus0000** [comment]
The moon dungeon seems to be GC, and the mars one is GP, maybe fix the generation and give the code to the GS people if possible?

**Comment by Dream-Master** [comment]
GS not support old outdated version.

**Comment by draknyte1** [comment]
> Fix oxygen tileentity lag

They don't even need to be tile entities.
Generic Tick handler + them as normal blocks would do and probably be more performant. (Just tick 1/s)

**Comment by botn365** [comment]
bugs/changes from bluebine
make it so if no valid launch destination dont launch the rocket if using space bar
make it so if that a rocket can launch with launch controller if no person is in it

presing space twice can stil launch the controller even if ther eisebnt enough fuel

**Comment by Regian24** [comment]
could you make it so that if you're in a rocket, you can't shift out? this would prevent craters and people dying because of accidentally pressing shift

**Comment by Regian24** [comment]
also maybe an item or an addon that reminds you when your oxygen is low (like >15%)

**Comment by Prometheus0000** [comment]
I think you mean _after_ it's launched. And before it lands, but that's sometimes buggy I think (with the mars lander).

But this should all be irrelevant once you can use the launcher and set it up. Though you still have to go the normal way to set up a launcher once.

**Comment by Regian24** [comment]
> I think you mean after it's launched. And before it lands, but that's sometimes buggy I think (with the mars lander).
Yep, while you're on earth and going up, you can't shift out

**Comment by Prometheus0000** [comment]
@botn365 Is this list up to date?

**Comment by botn365** [comment]
you will have to ask @glowredman sinse he has been doing al the gc/gs development now

**Comment by Prometheus0000** [comment]
@glowredman were you still going to work on these?

**Comment by glowredman** [comment]
At the moment I'd do only hotfixes, as I'm currently working on my own pack. Even when I have time again, I wouldn't know what needs to be done:
> redus agro range of mobs

Why though? I don't have the feeling that they are too dangerous, the planets are even meant to be more dangerous than the OW.
> Fix oxygen tileentity lag

I've stated my view on this already in [here](https://github.com/GTNewHorizons/Galacticraft/pull/16) and that I am not able to do anything aswell.
> make it so if no valid launch destination dont launch the rocket using space bar

You can always fly at least to Earth/Moon and imo one can expect the player to make sure he has enough fuel.
> if you're in a rocket, you can't shift out

Is this a bug or a request?
> fix presing space twice can stil launch the controller even if ther eisebnt enough fuel

Please explain.
> fix cargo rocketss from exploding whne using launch controller

Please explain.
> privetise frequanties of launch controller

Please elaborate.
