### ISSUE TITLE
Stable Update 2.1.2.0

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#8791]
### Your GTNH Discord Username

DreamMasterXXL

### Your Pack Version

2.1.2.0

### Your Proposal

We need a checklist what need to be done before stable 2.1.2.0 update

### Your Goal

We need a checklist what need to be done before stable 2.1.2.0 update

### Your Vision

We need a checklist what need to be done before stable 2.1.2.0 update

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
Finally close #7847 - new recipe for AE2 storage components - has been PR‘ed long time ago, still no consensus

**Comment by glowredman** [comment]
- [ ] #8577

**Comment by yukieiji** [comment]
- [ ]  Issues with GT enet change #8171
- [ ]  Visual Prospecting: GregTech + JourneyMap = <3 #8680

**Comment by boubou19** [comment]
- [ ]  https://github.com/SinTh0r4s/HydroEnergy/issues/30
- [ ]  #8778
- [ ]  #8466
- [ ]  #8321 (related to #8171 i think)

**Comment by Dream-Master** [comment]
> Finally close #7847 - new recipe for AE2 storage components - has been PR‘ed long time ago, still no consensus

Because I don’t merge it in this stage.

**Comment by Cata-bre** [comment]
[ ]  [Warp Theory Refactor and Rebalancing](https://github.com/GTNewHorizons/WarpTheory/pull/13)
[ ]  [Issue 8611](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8611)

**Comment by GTNH-Afx237v7** [comment]
> Because I don’t merge it in this stage.

Yes that is what I mean - we need to find and agreement on the recipe, then merge, then close.

**Comment by bombcar** [comment]
- [ ] #8628 
Given the aluminum change we should also include the proposed kanthal down-tier

**Comment by bombcar** [comment]
> > * [ ]    [Warp Theory Refactor and Rebalancing](https://github.com/GTNewHorizons/WarpTheory/pull/13)
> > * [ ]    [[RFC] Suggested new warp effects for Warp Theory #8611](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8611)
> 
> Edit: I don't know how to link correctly apparently; I can't get the green circle.

- [ ] #8611 

`- [ ] #8611`

**Comment by Steelux8** [comment]
> 
> 
>     * [ ]  [Change Kanthal Coils to be in MV instead of HV #8628](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8628)
>       Given the aluminum change we should also include the proposed kanthal down-tier

Looking at how the alum line is right now, this is essential. The EBF steps unlocked at LV to get aluminium and into the MV tier can only be changed at early-mid HV, after making a cleanroom, the HV circuit chain and the vac freezer. During MV, you have to keep using the LV EBF recipes.

**Comment by Dream-Master** [comment]
> > ```
> >   Given the aluminum change we should also include the proposed kanthal down-tier
> > ```
> 
> 
> Looking at how the alum line is right now, this is essential. The EBF steps unlocked at LV to get aluminium and into the MV tier can only be changed at early-mid HV, after making a cleanroom, the HV circuit chain and the vac freezer. During MV, you have to keep using the LV EBF recipes.

No it is not. Alu change works well with old coils in hv.

**Comment by Steelux8** [comment]
> No it is not. Alu change works well with old coils in hv.

How so? Carbon Dust can't be used with Alumina until post-vac freezer, and the same goes for smelting Aluminium Dust directly.

**Comment by Dream-Master** [comment]
Alumina + cryolite much cheaper than before

**Comment by Dream-Master** [comment]
Lv

**Comment by Steelux8** [comment]
Even if that's true, according to this chart I'm looking at, electrolyzing Alumina for Aluminium Dust and Oxygen can be done in an HV electrolyzer (unlocked with stainless steel) but it can only be processed after 2 new multis are built and the new circuit line has been started. 

Kanthal Coils even say in the tooltip that they are MV. I don't see any reason for them not to be, especially after the aluminium change.

**Comment by draknyte1** [comment]
As it’s stood for a long time, kanthal coils are pointless. As soon as you make them, you just make nichrome straight away. Moving them to actual MV makes lots of sense.

**Comment by Dream-Master** [comment]
Sure the kanthal buff is maybe a good change but it is not necessary because of the aluminium change.

**Comment by bombcar** [comment]
> Sure the kanthal buff is maybe a good change but it is not necessary because of the aluminium change.

True, as long as the cryolite is fixedindev the people who are late LV/early MV can use that. I'll note it on the Upcoming Changes page (which will become the wiki release page).

**Comment by Savallator** [comment]
Whoever included the AMDIForge-mod again (see #3204), can it be removed again? Since it is in 2.1.1.4QF2 currently and therefore Magnum torches are broken there.

**Comment by bombcar** [comment]
- [ ] #6868
This is marked code complete and would be nice if we can merge it in so our server stops going back to day zero

**Comment by slprime** [comment]
- [ ] https://github.com/GTNewHorizons/NotEnoughItems/issues/47
- [ ] https://github.com/GTNewHorizons/NotEnoughItems/issues/30
- [ ] https://github.com/GTNewHorizons/NotEnoughItems/issues/16
- [ ] https://github.com/GTNewHorizons/NotEnoughItems/issues/18

I can fix this issues

**Comment by D-Cysteine** [comment]
Some more suggestions, some of which might be too much work though:

 * [ ] Mark quests secret, and re-enable showing the view mode button by default in the quest book
 * [ ] Fix as many colliding / bugged recipes as we can
 * [ ] Decide on what we want to do for #gc-o2-lox-rework and implement it?

I could go through and try to compile a list of bugged recipes in 2.1.1.4, if desired, though there are very, very many.

**Comment by iouter** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7990

and update the nee.

**Comment by GTNH-Afx237v7** [comment]
The new dense covered cables still need a GTNH style recipe (currently just shapeless crafting of 4 covered cables).

**Comment by Dream-Master** [comment]
remove or make the platinum you get via Molecular Transformer more expensive
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/8573

**Comment by Glease** [comment]
>     * [ ]  Mark quests secret, and re-enable showing the view mode button by default in the quest book
> 
@D-Cysteine What else is needed on this subject? IIRC it's feature complete and merged already?

**Comment by D-Cysteine** [comment]
> > ```
> > * [ ]  Mark quests secret, and re-enable showing the view mode button by default in the quest book
> > ```
> 
> @D-Cysteine What else is needed on this subject? IIRC it's feature complete and merged already?

Currently, the view mode button (not view mode itself, but rather the button toggling it) is hidden by default, because there are some quests that it would show, which we actually want to hide even from view mode.

We need to actually go through the questbook and mark any quests that need to be secret with the new `SECRET` visibility. Then, we need to go into the Better Questing config and enable the view mode button by default. Unfortunately, I don't know which quests need to be secret. @Dream-Master might know?

**Comment by Dream-Master** [comment]
> > > ```
> > > * [ ]  Mark quests secret, and re-enable showing the view mode button by default in the quest book
> > > ```
> > 
> > 
> > @D-Cysteine What else is needed on this subject? IIRC it's feature complete and merged already?
> 
> Currently, the view mode button (not view mode itself, but rather the button toggling it) is hidden by default, because there are some quests that it would show, which we actually want to hide even from view mode.
> 
> We need to actually go through the questbook and mark any quests that need to be secret with the new `SECRET` visibility. Then, we need to go into the Better Questing config and enable the view mode button by default. Unfortunately, I don't know which quests need to be secret. @Dream-Master might know?

I dint have the time for set quests to be secret and enable view mode again. Will do this after the 2.1.1.5 dev version

**Comment by Dream-Master** [comment]
> Finally close #7847 - new recipe for AE2 storage components - has been PR‘ed long time ago, still no consensus

done

**Comment by Dream-Master** [comment]
> * [ ]  [[RFC] Dyson Swarm Ground Unit Balance & Recipes #8577](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8577)
> * [ ]  [Feature: Dyson Swarm (No Recipes / Balance yet!) Galaxy-Space-GTNH#7](https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/7)
> * [ ]  "Dyson Sphere Ground Unit" component recipes

will be done after release

**Comment by Dream-Master** [comment]
> * [ ]  [Change Kanthal Coils to be in MV instead of HV #8628](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8628)
>   Given the aluminum change we should also include the proposed kanthal down-tier

Done

**Comment by Dream-Master** [comment]
> * [ ]  [Add Schematica as an optional mod #245](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/245)
>   this apparently just works

Done

**Comment by Dream-Master** [comment]
> * [ ]  [Suggestion: Recipe Filters NotEnoughItems#47](https://github.com/GTNewHorizons/NotEnoughItems/issues/47)
> * [x]  [Suggestion: add NBT support for different bookmarks NotEnoughItems#30](https://github.com/GTNewHorizons/NotEnoughItems/issues/30)
> * [x]  [Feature Suggestion: Bookmark Locking NotEnoughItems#16](https://github.com/GTNewHorizons/NotEnoughItems/issues/16)
> * [x]  [GT++ bookmarked fluids changed after restart NotEnoughItems#18](https://github.com/GTNewHorizons/NotEnoughItems/issues/18)
> 
> I can fix this issues

@mitchej123 can you add this or is this just for next release ? (first checkbox)

**Comment by Dream-Master** [comment]
> Some more suggestions, some of which might be too much work though:
> 
> * [ ]  Mark quests secret, and re-enable showing the view mode button by default in the quest book
> * [ ]  Fix as many colliding / bugged recipes as we can
> * [ ]  Decide on what we want to do for #gc-o2-lox-rework and implement it?
> 
> I could go through and try to compile a list of bugged recipes in 2.1.1.4, if desired, though there are very, very many.

Will add the secret quest stuff tomorrow

**Comment by Dream-Master** [comment]
> * [ ]  [add Just Enough Calculation ported from 1.16 #7990](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7990)
> 
> and update the nee.

@iouter let me know when it is done

**Comment by bombcar** [comment]
In checking the current zip I noted the following are either not on Jenkins or are outdated in the zip/jenkins:

[NEI-Integration](https://github.com/GTNewHorizons/NEI-Integration) (has code fixes)
Biomes of Plenty
[StorageDrawers](https://github.com/GTNewHorizons/StorageDrawers) (got split into five, but the "original" one is still there
[WitcheryExtras](https://github.com/GTNewHorizons/WitcheryExtras) (has code changes)
[BloodMagic](https://github.com/GTNewHorizons/BloodMagic) (has code changes, renamed master)

**Comment by Savallator** [comment]
Could we maybe get this #8806 into 2.1.2.0 ? It would be a small change, but help a lot with scalability and especially server performance.

**Comment by boubou19** [comment]
2.1.2.0 came out this night, so nope, sorry. Maybe in the next one.

**Comment by Savallator** [comment]
Oh lol, sorry, too late^^ I was deceived by this issue being still pinned lol
