### ISSUE TITLE
todo list for pollution before 2.1.2.0

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8935]
- [x] fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8023: looks like it got fixed at some point in dev
- [x] make pollution in GT++ configurable
- [x] make new tiers of electric air filters
- [x] add new recipes for the new electric air filters tier
- [ ] rework gt++ scrubber or add one to GT
- [ ] eventual rebalance of pollution through config if needed
