### ISSUE TITLE
Adjust AE cells (again) before release

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9041]
### Your GTNH Discord Username

Mitchej1984 (trust me!!!)

### Your Pack Version

dev

### Todo

Current state of cells:
![image](https://user-images.githubusercontent.com/54497873/145331703-36bef0c1-4895-4935-b519-a44314e85d09.png)

Proposal:
Up-tier all circuits by 1 and make 1024, 4096 and 16384 cells use that associated highest circuit tiers field gen.

So with this proposal 16384ks would use say 1 UHV field gen (meaning UEV circuits are used, meets requirements of discord conversation).

Can also be an assline recipe maybe? Not really needed.

@boubou19 

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
and make the drawer controller take a UEV circuit also. You get two free from quests, that should be enough 🗡️

**Comment by boubou19** [comment]
i guess we could gate some of them with an assline (1kk and above) but adding field gens and a circuit shift is a nope from me. If you want to propose a dumb scaling just so 16kk reaches UEV to match the expectations of the infi chest price, then we should change its recipe instead.

**Comment by AtomicGrog** [comment]
Am guessing some don't understand the implications of the top end boards being used. 16kk already needs same boards as UEV circuits as far as I can see, seems a fair balance imho. If there's concern over lack of certus 'volume' why not throw in some compressed/double/triple/quad certus blocks, with recipes similar to the cobblestone processes for bedrock - That way we can imagine all the recipes stored in the certus structure.

**Comment by Sphyix** [comment]
I'd say let's use the Quantum Circuits, but then I want the infi chest to make me coffee aswell.
I don't seriously understand this request colen, recursion for the 16384k is still there and the most expensive thing in there is like a stack of indium, 32 stacks of platinum, and a bunch of low tier materials like iron, copper etc..
Why would you want a new recipe, with the old recursive one still in the game, that costs like 20x more than the old one?

Right now making a 16384k costs 4 UV and 16 LuV circuits, the rest of materials needed at the tier when you need to make the infi chest can't even be considered a cost. Not even sure if the 16 LuV circuits are considered a cost tbh.

So the change that was done is already kind of a nerf for the cost, as now the 16384k costs 16 ZPM circuits and 4 UV, but a buff for the time taken as it is removing the recursion. That's good for server tps as an ME system autocrafting a 16384k with recursion is kinda really heavy, and that's good for the annoying time taken to make it compared to how much it doesn't cost.

Plus have you noticed everyone is spamming 64k or lower cells? Maybe someone is going 256k but that's it. Have you wondered why?
Upgrading them is just a cost and you don't get benefits.

I still think recursion rate is wrong and should be 3:1 to encourage upgrading instead of spamming of lower tier cells, and the cost of the new recipes without recursion could still be too high compared to other storage options.

**Comment by bombcar** [comment]
Sounds like inf chest needs to be build out of 256ks …

**Comment by GTNH-Colen** [comment]
I think people are being a bit disingenuous here, this change is still a huge buff. Lets take a look at the 16384k for example, in the old version it would require approximately the following highlights:

8500 diamonds
87000 redstone
80000 gold
65000 certus
12000 copper
etc

Now in the new version we have:
198 diamonds
63 redstone
0 gold
0 certus
2500 copper

Do I really need to say more? This is a huge drop in costs here, hence why we need to balance this a bit more before final release.

**Comment by Sphyix** [comment]
So 8.5k diamond is a big price to pay at UV? LOL

**Comment by bombcar** [comment]
> So 8.5k diamond is a big price to pay at UV? LOL

I think a distinction between "tedium" price and "difficulty" price can be made. Everything on that list goes brrrr with a voidminer in the right place; it's just a matter of collecting it. In fact, it all could be collected in LV.

I still think compressed cereus quartz blocks would provide a "thematic" explanation on how the thing can store so much.

**Comment by Sphyix** [comment]
> I think a distinction between "tedium" price and "difficulty" price can be made. Everything on that list goes brrrr with a voidminer in the right place; it's just a matter of collecting it. In fact, it all could be collected in LV.
> 
> I still think compressed cereus quartz blocks would provide a "thematic" explanation on how the thing can store so much.

I completely agree with you, I completely disagree with the request of using UEV for 16384k
They are UV, they have to stay UV.

**Comment by GTNH-Colen** [comment]
> So 8.5k diamond is a big price to pay at UV? LOL Just a reminder, at LuV you can get a void miner

Slashing the cost to such a degree, to the point where cells don't even use certus anymore seems insane. 8500 diamonds isn't a lot but cutting it to 198 is crazy, I could make 42 MAX tier cells for the same cost as before and yet you seem to be imagining this as a nerf? How?

> So the change that was done is already kind of a nerf for the cost

🤔🤔🤔

I'm fine with getting rid of recursion and even making cells cheaper than before but this is a massive buff and we can't pretend otherwise.

**Comment by Sphyix** [comment]
Adding certus quartz back in is a good idea.
But don't tell me that copper, iron and diamond is something that you consider a cost at LuV+

**Comment by GTNH-Afx237v7** [comment]
How many single items can a 16384K hold, assuming only one item type is used?

**Comment by Sphyix** [comment]
According to google, 2.080.768 stacks of a single item or 1.064.960 stacks of 63 different items

**Comment by GTNH-Afx237v7** [comment]
So 133 Million items of one type, just over twice the capacity of a super chest 5 (64M). And the super chest costs less than that iirc, has auto-voiding and is now transportable. 
Personally I don’t think the new recipes are buffed too much, I wanted to use drives instead of arrays of chests but the costs discrepancy kept me away from doing so. Now it looks much better.

**Comment by boubou19** [comment]
> So 133 Million items of one type, just over twice the capacity of a super chest 5 (64M). And the super chest costs less than that iirc, has auto-voiding and is now transportable.
> Personally I don’t think the new recipes are buffed too much, I wanted to use drives instead of arrays of chests but the costs discrepancy kept me away from doing so. Now it looks much better.

See? People just avoid AE cells because they are overpriced in comparison to other alternatives. So why should we nerf them to such extent?

**Comment by querns** [comment]
It's pretty important for AE2 cells to be cheap. The tradeoff is recipe complexity vs. server friendliness. Right now, a drawer with a single emerald upgrade is slightly MORE effective than a 16k cell that's been set to one item in a cell workbench. Cells perform far better compared to drawers in terms of TPS (and FPS too, but you can hide drawers out of render distance pretty easily.) Therefore, it's a really good idea to sacrifice recipe complexity of AE2 cells to combat drawer spam. Making the cells cheap is a good carrot to go along with the maximum drawer cube size stick.

I'd actually like to see super cheap 1 item cells to compete with drawers, but I have no idea how difficult it is to add new AE2 cells so I haven't really bothered coming up with a proposal for them.

**Comment by bombcar** [comment]
Let’s just ban drawer controllers from ae2

a wall of drawers is nice in mv but not needed when you have ae2

**Comment by Glease** [comment]
I personally would put a silly suggestion tag on this one, if not close this outright, but oh well.
